# Copyright 2024 Province of Alberta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Summarize population growth
#'
#' Provides a summary of yearly population growth (\eqn{\lambda}) estimates from
#' simulations.
#'
#' @param growth A data frame generated by `bbr_growth()`.
#'
#' @return A data frame. The columns are listed in the format section.
#' @export
#'
#' @format The return object has these columns:
#' \describe{
#' \item{PopulationName}{Population name}
#' \item{Year}{Year sampled}
#' \item{S}{Estimated survival}
#' \item{R}{Estimated recruitment}
#' \item{estimate}{Estimated population growth (lambda)}
#' \item{se}{SE}
#' \item{lower}{Percentile 95% confidence limits}
#' \item{upper}{Percentile 95% confidence limits}
#' \item{prop_lgt1}{Proportion simulations where lambda>1}
#' \item{mean_sim_survival}{Mean simulated survival value}
#' \item{mean_sim_recruitment}{Mean simulated recruitment value}
#' \item{mean_sim_growth}{Mean simulated population growth (lambda) value}
#' \item{median_sim_growth}{Median simulated population growth (lambda) value}
#' }
#'
#' @examples
#' \dontrun{
#' bbr_growth_summarize(growth_est)
#' }
bbr_growth_summarize <- function(growth) {
  chk::check_names(growth, c(
    "PopulationName", "Year", "S", "R", "estimate", "se", "lower", "upper",
    "prop_lgt1", "ran_r", "ran_s"
  ))

  chk::check_data(
    growth,
    values = list(
      PopulationName = character(),
      Year = integer(),
      S = numeric(),
      R = numeric(),
      estimate = numeric(),
      se = numeric(),
      lower = numeric(),
      upper = numeric(),
      prop_lgt1 = numeric()
    )
  )
  chk::chk_is(growth$ran_s, "AsIs")
  chk::chk_is(growth$ran_r, "AsIs")
  chk::chk_numeric(growth$ran_s[[1]])
  chk::chk_numeric(growth$ran_r[[1]])
  
  growth <- growth |>
    dplyr::mutate(
      mean_sim_survival = purrr::map_dbl(.data$ran_s, mean),
      mean_sim_recruitment = purrr::map_dbl(.data$ran_r, mean),
      lambda = purrr::map2(.data$ran_s, .data$ran_r, function(s, r) {
        s / (1 - r)
      }),
      mean_sim_growth = purrr::map_dbl(.data$lambda, mean),
      median_sim_growth = purrr::map_dbl(.data$lambda, median)
    ) |>
    dplyr::select(!c("ran_s", "ran_r", "lambda"))

  growth[-(1:2)] <- round(growth[-(1:2)], 3)
  growth
}
