# Copyright 2024 Province of Alberta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Summarize lambda
#'
#' Provides a summary of yearly \eqn{\lambda} estimates from simulations.
#'
#' @param lambda A list object generated by `bbr_lambda_simulate()`.
#'
#' @return A data frame. The columns are listed in the format section.
#' @export
#'
#' @format The return object has these columns:
#' \describe{
#' \item{PopulationName}{Population name}
#' \item{Year}{Year sampled}
#' \item{S}{Estimated survival}
#' \item{R}{Estimated recruitment}
#' \item{Lambda}{Estimated lambda}
#' \item{Lambda_SE }{SE}
#' \item{Lambda_CIL}{Percentile 95% confidence limits}
#' \item{Lambda_CIU }{Percentile 95% confidence limits}
#' \item{Prop_LGT1 }{Proportion simulations where lambda>1}
#' \item{meanSimSurv}{Mean simulated survival value}
#' \item{meanRsim}{Mean simulated recruitment value}
#' \item{meanSimLambda }{Mean simulated lambda value}
#' \item{medianSimLambda}{Median simulated lambda value}
#' }
#'
#' @examples
#' \dontrun{
#' bbr_lambda_summarize(lambda)
#' }
bbr_lambda_summarize <- function(lambda) {
  chk::chk_not_empty(lambda, x_name = "lambda")
  chk::check_names(lambda, names = c("summary", "raw_values"))

  summary <- lambda$summary

  chk::check_data(
    summary,
    values = list(
      PopulationName = character(),
      Year = integer(),
      S = numeric(),
      R = numeric(),
      Lambda = numeric(),
      Lambda_SE = numeric(),
      Lambda_CIL = numeric(),
      Lambda_CIU = numeric(),
      Prop_LGT1 = numeric(),
      meanSimSurv = numeric(),
      meanRsim = numeric(),
      meanSimLambda = numeric(),
      medianSimLambda = numeric()
    )
  )

  summary[c(3:12)] <- round(summary[c(3:12)], 3)
  summary
}
