# Copyright 2024 Province of Alberta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Summarize lambda
#'
#' Provides a summary of yearly \eqn{lambda} estimates from simulations.
#'
#' @param lambda Summary output object generated by `lambda_sim()`
#'
#' @return The following values are given as a data frame.  See LambdaSim for
#'   more details on each row.
#' @export
#'
#' @format A tibble with columns:
#' \describe{
#' \item{PopulationName}{Population name}
#' \item{Year}{Year sampled}
#' \item{S}{Estimated survival}
#' \item{R}{Estimated recruitment}
#' \item{Lambda}{Estimated lambda (S/(1-R))}
#' \item{SE_Lambda }{SE}
#' \item{Lambda_LCL}{Percentile 95% confidence limits}
#' \item{Lambda_UCL }{Percentile 95% confidence limits}
#' \item{Prop_LGT1 }{Proportion simulations where lambda>1}
#' \item{meanSimSurv}{Mean simulated survival value}
#' \item{meanRsim}{Mean simulated recruitment value}
#' \item{meanSimLambda }{Mean simulated lambda value}
#' \item{medianSimLambda}{Median simulated lambda value}
#' }
#'
#' @examples
#' summarize_lambda(lambda)
summarize_lambda <- function(lambda) {
  Lsum <- lambda$Summary
  Lsum[c(3:12)] <- round(Lsum[c(3:12)], 3)
  print(Lsum)
  Lsum
}
