# Copyright 2024 Province of Alberta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Summarize lambda
#'
#' Provides a summary of yearly \eqn{\lambda} estimates from simulations.
#'
#' @param lambda A list object generated by `bbr_lambda()`.
#'
#' @return A data frame. The columns are listed in the format section.
#' @export
#'
#' @format The return object has these columns:
#' \describe{
#' \item{PopulationName}{Population name}
#' \item{Year}{Year sampled}
#' \item{S}{Estimated survival}
#' \item{R}{Estimated recruitment}
#' \item{Lambda}{Estimated lambda}
#' \item{Lambda_SE }{SE}
#' \item{Lambda_CIL}{Percentile 95% confidence limits}
#' \item{Lambda_CIU }{Percentile 95% confidence limits}
#' \item{prop_lgt1 }{Proportion simulations where lambda>1}
#' \item{mean_sim_survival}{Mean simulated survival value}
#' \item{mean_sim_recruitment}{Mean simulated recruitment value}
#' \item{mean_sim_lambda }{Mean simulated lambda value}
#' \item{median_sim_lambda}{Median simulated lambda value}
#' }
#'
#' @examples
#' \dontrun{
#' bbr_lambda_summarize(lambda)
#' }
bbr_lambda_summarize <- function(lambda) {
  chk::chk_not_empty(lambda, x_name = "lambda")
  chk::check_names(lambda, names = c("summary", "raw_values"))
  
  summary <- lambda$summary
  
  chk::check_names(summary, c(
    "PopulationName", "Year", "S", "R", "estimate", "se", "lower", "upper",
    "prop_lgt1", "RanR", "RanS"))
  
  chk::check_data(
    summary,
    values = list(
      PopulationName = character(),
      Year = integer(),
      S = numeric(),
      R = numeric(),
      estimate = numeric(),
      se = numeric(),
      lower = numeric(),
      upper = numeric(),
      prop_lgt1 = numeric()
    )
  )
  # TODO: check RanR and RanS columns but they are lists
  
  summary <- summary |>
    dplyr::mutate(
      mean_sim_survival = purrr::map_dbl(.data$RanS, mean),
      mean_sim_recruitment = purrr::map_dbl(.data$RanR, mean)
      # lambda = purrr::map2(.data$RanS, .data$RanR, function(s,r) { s / (1 - r) }),
      # mean_sim_lambda = purrr::map_dbl(.data$lambda, mean),
      # median_sim_lambda = purrr::map_dbl(.data$lambda, median)
    ) |>
    dplyr::select(!c("RanS", "RanR"))
  
  summary[-(1:2)] <- round(summary[-(1:2)], 3)
  summary
}
