# Copyright 2024 Province of Alberta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Plot population growth
#'
#' A plot of population growth (\eqn{\lambda}) estimates is given for the
#' population unit.
#'
#' @param growth A data frame generated by `bbr_growth()`.
#' @return A ggplot object.
#' @export
#'
#' @examples
#' \dontrun{
#' bbr_plot_growth(growth_est)
#' }
bbr_plot_growth <- function(growth) {
  growth$CaribouYear <- as.character(growth$CaribouYear)

  chk::check_data(
    growth,
    values = list(
      PopulationName = character(),
      CaribouYear = character(),
      estimate = numeric(),
      lower = numeric(),
      upper = numeric()
    )
  )

  ggplot(growth, aes(.data$CaribouYear, .data$estimate)) +
    geom_point(color = "red", size = 3) +
    geom_errorbar(
      aes(x = .data$CaribouYear, ymin = .data$lower, ymax = .data$upper),
      color = "steelblue"
    ) +
    geom_hline(yintercept = 1) +
    facet_wrap(~PopulationName, ncol = 1) +
    xlab("Caribou Year") +
    ylab("Lambda estimate") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
}
