#' Plot lambda distributions
#'
#' Provides histograms of simulated \eqn{lambda} values for a chose population
#' unit.
#'
#' @param lambda Summary output object generated by `lambda_sim()`
#' @param population
#'
#' @return A ggplot object 
#' @export
#'
#' @details Plots are generated that show the distribution of simulated λ
#' values, the mean estimate (red line).  In addition, a hashed line indicates
#' where \eqn{lambda = 1}.  Plots allow users to evaluate the symmetry of the distributions
#' of \eqn{lambda}.
#'
#'
#' @examples
#' \dontrun{
#' summarize_lambda(lambda) 
#' }
plot_lambda_distributions<-function(lambda,population){
  #subset data set for target population
  Ld<-subset(lambda$RawValues,lambda$RawValues$PopulationName==population) 
  RL<-subset(lambda$Summary,lambda$Summary$PopulationName==population) 
  Lraw<-lambda$RawValues
  
  #screen out sims where random lambda is NA (likely due to S=1 with 0 variance)
  #year is still plotted as a line but with no distribution
  LrawR<-subset(Lraw,is.na(Lraw$RanLambda)==F)
  
  #plot estimated lambda for each year as a red line with 
  #a black hashed line indicates lambda=1.
  ggplot(LrawR,aes(RanLambda))+
    geom_histogram(bins=30,fill="tan",color="black")+
    geom_vline(data=RL, aes(xintercept=Lambda),  color="red")+
    geom_vline(xintercept=1,linetype=2,color="black")+
    scale_x_continuous(breaks=seq(0.2,1.4,0.4))+
    facet_wrap(~Year)+
    xlab("Lambda Values")+
    ylab("Frequencies")+
    theme_bw()
}