# Copyright 2024 Province of Alberta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Plot population growth distributions
#'
#' Create histograms of simulated population growth (\eqn{\lambda}) values for a
#' chosen population unit.
#'
#' @param growth A data frame generated by `bbr_growth()`.
#'
#' @return A ggplot object.
#' @export
#'
#' @details Plots are generated that show the distribution of simulated
#'   population growth (\eqn{\lambda}) values, the mean estimate (red line).  In
#'   addition, a hashed line indicates where \eqn{\lambda = 1}.  Plots allow
#'   users to evaluate the symmetry of the distributions of \eqn{\lambda}.
#'
#' @examples
#' \dontrun{
#' bbr_plot_growth_distributions(growth_est)
#' }
bbr_plot_growth_distributions <- function(growth) {
  chk::chk_data(growth)
  chk_population(growth)
  
  Ld <- growth |>
    tidyr::unnest(cols = c("ran_s", "ran_r")) |>
    dplyr::mutate(RanLambda = .data$ran_s / (1 - .data$ran_r))

  # screen out sims where random lambda is NA (likely due to S=1 with 0 variance)
  # year is still plotted as a line but with no distribution
  LrawR <- subset(Ld, is.na(Ld$RanLambda) == FALSE)
  
  # set lambda limits for x axis based all lambda--this reduces influence of outliers
  xmin <- quantile(LrawR$RanLambda, 0.0001)
  xmax <- quantile(LrawR$RanLambda, 0.99)
  # make sure that limits are still within range of lambda estimates for estimates with no CI's
  xmax <- ifelse(xmax <= max(growth$estimate), max(growth$estimate) + 0.05, xmax)
  xmin <- ifelse(xmin >= min(growth$estimate), min(growth$estimate) - 0.05, xmin)
  
  # subset data based on xlimits-this works better than using xlim or coord_cartesian in ggplot
  LrawR <- subset(LrawR, LrawR$RanLambda >= xmin & LrawR$RanLambda <= xmax)
  
  # plot estimated lambda for each year as a red line with
  # a black hashed line indicates lambda=1.
  ggplot(LrawR, aes(.data$RanLambda)) +
    geom_histogram(bins = 30, fill = "tan", color = "black") +
    geom_vline(data = growth, aes(xintercept = .data$estimate), color = "red") +
    geom_vline(xintercept = 1, linetype = 2, color = "black") +
    facet_wrap(~ .data$Year) +
    xlab("Lambda Values") +
    ylab("Frequencies") +
    theme_bw()
}
