# Copyright 2024 Province of Alberta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Plot lambda
#'
#' Uses output from `bbr_lambda_simulate()`.
#'
#' @param lambda summary output object generated by `bbr_lambda_simulate()`.
#' @return A ggplot object.
#' @export
#'
#' @details
#' A plot of \eqn{lambda} estimates is given for each population unit.
#'
#' @examples
#' \dontrun{
#' bbr_plot_lambda(lambda_est)
#' }
bbr_plot_lambda <- function(lambda) {
  chk::chk_is(lambda, "list")
  chk::check_names(lambda, names = c("summary"))
  chk_has_data(lambda$summary)

  plotdat <- lambda$summary
  plotdat$Year <- as.character(plotdat$Year)

  chk::check_data(
    plotdat,
    values = list(
      PopulationName = character(),
      Year = character(),
      Lambda = numeric(),
      Lambda_LCL = numeric(),
      Lambda_UCL = numeric()
    )
  )

  ggplot(plotdat, aes(.data$Year, .data$Lambda)) +
    geom_point(color = "red", size = 3) +
    geom_errorbar(
      aes(x = .data$Year, ymin = .data$Lambda_LCL, ymax = .data$Lambda_UCL),
      color = "steelblue"
    ) +
    geom_hline(yintercept = 1) +
    facet_wrap(~PopulationName, ncol = 1) +
    xlab("Year") +
    ylab("Lambda estimate") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
}
