#' Plot recruitment
#'
#' Uses output from Recruitment to plot yearly estimates
#'
#' @param recruitment Input summary data frame generated by Recruitment
#'
#' @return A ggplot object
#' @export
#'
#' @details
#' A plot of yearly survival is given for each population unit.
#'
#'
#' @examples
#' \dontrun{
#' plot_recruitment(recruitment_est)
#' }
plot_recruitment <- function(recruitment) {
  ggplot(recruitment, aes(Year, R)) +
    geom_point(color = "red", size = 3) +
    geom_errorbar(aes(x = Year, ymin = R_CIL, ymax = R_CIU), color = "steelblue") +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    xlab("Year") +
    ylab("Recruitment") +
    facet_wrap(~PopulationName, ncol = 1) +
    theme_bw(base_size = 14)
}
