#' Plot survival
#'
#' Uses output from `km_survival()` to plot yearly estimates.
#'
#' @param survival Input summary data frame generated by `km_survival()`
#'
#' @return A ggplot object
#' @export
#'
#' @details
#' A plot of yearly survival is given for each population unit.
#'
#' @examples
#' \dontrun{
#' plot_survival(survival_est)
#' }
plot_survival <- function(survival) {
  ggplot(survival, aes(Year, S)) +
    geom_point(color = "red", size = 3) +
    geom_errorbar(aes(x = Year, ymin = S_CIL, ymax = S_CIU), color = "steelblue") +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    xlab("Year") +
    ylab("Adult female survival") +
    facet_wrap(~PopulationName, scales = "free_x") +
    theme_bw(base_size = 14)
}
