#' Plot lambda
#' 
#' Uses output from LambdaSim 
#'
<<<<<<< HEAD
#' @param lambda Summary output object generated by LambdaSim 
=======
#' @param L Summary output object generated by LambdaSim 
>>>>>>> 95e64074403147b059f00c60aa3278542418d886
#'
#' @return A ggplot object 
#' @export
#' 
#' @details
#' A plot of \eqn{lambda} estimates is given for each population unit 
#' 
#'
#' @examples
#' plot_lambda(lambda_est)
plot_lambda<-function(lambda){
  plotdat<-lambda$Summary
  
  ggplot(plotdat,aes(Year,Lambda))+
    geom_point(color='red',size=3)+
    geom_errorbar(aes(x=Year,ymin=Lambda_LCL, ymax=Lambda_UCL),color='steelblue')+
    geom_hline(yintercept=1)+
    facet_wrap(~PopulationName,ncol=1)+
    xlab("Year")+
    ylab("Lambda estimate")+
    theme_bw()  
}
