# Copyright 2024 Province of Alberta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Plot recruitment
#'
#' Uses output from Recruitment to plot yearly estimates
#'
#' @param recruitment Input summary data frame generated by Recruitment
#'
#' @return A ggplot object
#' @export
#'
#' @details
#' A plot of yearly survival is given for each population unit.
#'
#'
#' @examples
#' \dontrun{
#' plot_recruitment(recruitment_est)
#' }
plot_recruitment <- function(recruitment) {
  ggplot(recruitment, aes(.data$Year, .data$R)) +
    geom_point(color = "red", size = 3) +
    geom_errorbar(
      aes(x = .data$Year, ymin = .data$R_CIL, ymax = .data$R_CIU), 
      color = "steelblue"
    ) +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    xlab("Year") +
    ylab("Recruitment") +
    facet_wrap(~PopulationName, ncol = 1) +
    theme_bw(base_size = 14)
}
