#' Plot lambda
#'
#' Uses output from LambdaSim
#'
#' @param lambda Summary output object generated by LambdaSim
#' @return A ggplot object
#' @export
#'
#' @details
#' A plot of \eqn{lambda} estimates is given for each population unit
#'
#'
#' @examples
#' \dontrun{
#' plot_lambda(lambda_est)
#' }
plot_lambda <- function(lambda) {
  plotdat <- lambda$Summary

  ggplot(plotdat, aes(Year, Lambda)) +
    geom_point(color = "red", size = 3) +
    geom_errorbar(aes(x = Year, ymin = Lambda_LCL, ymax = Lambda_UCL), color = "steelblue") +
    geom_hline(yintercept = 1) +
    facet_wrap(~PopulationName, ncol = 1) +
    xlab("Year") +
    ylab("Lambda estimate") +
    theme_bw()
}
